# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcfc12e24672e600ca286e4043a27ec3829e66991fdbe54854dc39bf9e2d58ef438b5fea66e43cb2b04f274b8e43c2d0d89122194368f8ac09cc03217696d7c0

test:
  secret_key_base: f0ce6e8a374c14467f0d66db76301883f3f0b13737a7f6c5fa020f9f9fd60d5bbb4ccfe0196b7914670d4d936a830d9c257d2452cc2e34b31d95ba0d1a11c1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
